import { Stack, Grid } from "@mui/material"

import type { GetServerSidePropsContext, NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

import DecoratedTitle from "src/components/common/decaratedTitle"

import LatestNews from "src/components/news/latestNews"
import NewsCard from "src/components/news/newsCard"
import { News } from "src/model"
import { getNewsFromCacheAndSync } from "src/queries/serverSideCache"
import theme from "src/theme"

interface HomeProps {
  news: News[]
  latestNews?: News
}

const Home: NextPage<HomeProps> = (props) => {
  const { news, latestNews } = props

  return (
    <Stack>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>{latestNews && <LatestNews news={latestNews} />}</section>
        <section>
          <Stack p={{ xs: 4, lg: theme.spacing(4, 0, 4, "40px") }}>
            <Stack alignItems="center">
              <DecoratedTitle title="Other news" />
            </Stack>
            <Grid container spacing={4}>
              {news.map((item) => (
                <Grid item key={item.id}>
                  <NewsCard news={item} />
                </Grid>
              ))}
            </Grid>
          </Stack>
        </section>
      </main>

      <footer></footer>
    </Stack>
  )
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const news: News[] = await getNewsFromCacheAndSync()
  const latestNews = news.shift()
  return {
    props: {
      news,
      latestNews,
    },
  }
}

export default Home
