import { Stack, Grid } from "@mui/material"

import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

import DecoratedTitle from "src/components/common/decaratedTitle"

import LatestNews from "src/components/news/latestNews"
import NewsCard from "src/components/news/newsCard"
import theme from "src/theme"

const Home: NextPage = () => {
  return (
    <Stack>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <LatestNews />
        </section>
        <section>
          <Stack p={{ xs: 4, lg: theme.spacing(4, 0, 4, "40px") }}>
            <Stack alignItems="center">
              <DecoratedTitle title="Other news" />
            </Stack>
            <Grid container spacing={4}>
              <Grid item>
                <NewsCard random={1} />
              </Grid>
              <Grid item>
                <NewsCard random={2} />
              </Grid>
              <Grid item>
                <NewsCard random={3} />
              </Grid>
              <Grid item>
                <NewsCard random={4} />
              </Grid>
              <Grid item>
                <NewsCard random={5} />
              </Grid>
            </Grid>
          </Stack>
        </section>
      </main>

      <footer></footer>
    </Stack>
  )
}

export default Home
